# Generated by Django 2.2.7 on 2019-11-18 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('view_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
