# Generated by Django 2.2.7 on 2020-01-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_app', '0002_race_race_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_id',
            field=models.CharField(default='hoge', max_length=200),
        ),
    ]
