# Generated by Django 2.2.7 on 2020-02-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_race_race_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='race_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='race',
            name='race_date',
        ),
        migrations.RemoveField(
            model_name='race',
            name='race_id',
        ),
        migrations.AddField(
            model_name='race',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='predict',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='result',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
