# Generated by Django 3.1 on 2020-08-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=50)),
                ('race_horse_number', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('clockwise', models.CharField(max_length=1)),
                ('field_type', models.CharField(max_length=1)),
                ('field_condition', models.CharField(max_length=1)),
                ('weather', models.CharField(max_length=1)),
                ('date_time', models.DateTimeField(null=True)),
                ('result', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
