# Generated by Django 3.1 on 2020-10-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=50)),
                ('race_horse_number', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('clockwise', models.CharField(max_length=1)),
                ('field_type', models.CharField(max_length=1)),
                ('field_condition', models.CharField(max_length=1)),
                ('weather', models.CharField(max_length=1)),
                ('date_time', models.DateTimeField(null=True)),
                ('result', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_number', models.IntegerField()),
                ('frame_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gen', models.CharField(max_length=1)),
                ('weight', models.IntegerField()),
                ('weight_diff', models.IntegerField()),
                ('burden_weight', models.IntegerField()),
                ('one_before_odd', models.FloatField()),
                ('one_before_popular', models.IntegerField()),
                ('one_before_rank', models.IntegerField()),
                ('one_before_time', models.IntegerField()),
                ('one_before_elapsed_day', models.IntegerField()),
                ('one_before_distance', models.IntegerField()),
                ('one_before_field_type', models.CharField(max_length=1)),
                ('one_before_field_condition', models.CharField(max_length=1)),
                ('one_before_weather', models.CharField(max_length=1)),
                ('two_before_odd', models.FloatField()),
                ('two_before_popular', models.IntegerField()),
                ('two_before_rank', models.IntegerField()),
                ('two_before_time', models.IntegerField()),
                ('two_before_elapsed_day', models.IntegerField()),
                ('two_before_distance', models.IntegerField()),
                ('two_before_field_type', models.CharField(max_length=1)),
                ('two_before_field_condition', models.CharField(max_length=1)),
                ('two_before_weather', models.CharField(max_length=1)),
                ('three_before_odd', models.FloatField()),
                ('three_before_popular', models.IntegerField()),
                ('three_before_rank', models.IntegerField()),
                ('three_before_time', models.IntegerField()),
                ('three_before_elapsed_day', models.IntegerField()),
                ('three_before_distance', models.IntegerField()),
                ('three_before_field_type', models.CharField(max_length=1)),
                ('three_before_field_condition', models.CharField(max_length=1)),
                ('three_before_weather', models.CharField(max_length=1)),
                ('four_before_odd', models.FloatField()),
                ('four_before_popular', models.IntegerField()),
                ('four_before_rank', models.IntegerField()),
                ('four_before_time', models.IntegerField()),
                ('four_before_elapsed_day', models.IntegerField()),
                ('four_before_distance', models.IntegerField()),
                ('four_before_field_type', models.CharField(max_length=1)),
                ('four_before_field_condition', models.CharField(max_length=1)),
                ('four_before_weather', models.CharField(max_length=1)),
                ('five_before_odd', models.FloatField()),
                ('five_before_popular', models.IntegerField()),
                ('five_before_rank', models.IntegerField()),
                ('five_before_time', models.IntegerField()),
                ('five_before_elapsed_day', models.IntegerField()),
                ('five_before_distance', models.IntegerField()),
                ('five_before_field_type', models.CharField(max_length=1)),
                ('five_before_field_condition', models.CharField(max_length=1)),
                ('five_before_weather', models.CharField(max_length=1)),
                ('race_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
            ],
        ),
    ]
