# Generated by Django 3.1 on 2020-08-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_number', models.IntegerField()),
                ('frame_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gen', models.CharField(max_length=1)),
                ('weight', models.IntegerField()),
                ('weight_diff', models.IntegerField()),
                ('burden_weight', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
            ],
        ),
    ]
