# Generated by Django 2.2.7 on 2020-03-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_auto_20200215_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='predict',
        ),
    ]
